### ISSUE TITLE
version 0.13.2 missing class in the jar file?

### ISSUE THREAD

**Issue by nogasgofast** [trentech/ProjectPortals#25]
Honestly this is just after upgrading to 5.0 API for like 10 plugins. But the error seemed specific enough to post here.

```
[01:02:22 ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=pjp, name=ProjectPortals, version=0.13.2, description=One
stop shop for all things portal, url=http://github.com/TrenTech/ProjectPortals, authors=[TrenTech], source=mods/projectportals-5.0.0-0.13.2.ja
r}
java.lang.NoClassDefFoundError: com/gmail/trentech/helpme/help/Usage
        at com.gmail.trentech.pjp.Main.onInitialization(Main.java:94) ~[Main.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_Main_onInitialization40.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-6.0.0-BETA-1
49]
```

**Comment by trentech** [comment]
09a515e9fa258afdbf6d4505c71b193e5c302505
